### ISSUE TITLE
setting njobs to more than 1 doesn't work.

### ISSUE THREAD

**Issue by ajinkyaT** [rsteca/sklearn-deap#33] opened 2017-08-19 04:23 UTC

**Comment by rsteca** [comment] 2017-08-20 17:51
It works for me, what error are you getting?

**Comment by ajinkyaT** [comment] 2017-08-22 02:29
It throws the following error in Jupyter notebook:
`Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/ajinkya/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ajinkya/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ajinkya/anaconda3/lib/python3.6/multiprocessing/pool.py", line 429, in _handle_results
    task = get()
  File "/home/ajinkya/anaconda3/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 3 required positional arguments: 'node_def', 'op', and 'message'
`
Though njobs=1 works fine

**Comment by rsteca** [comment] 2017-09-07 14:33
I have never tried this in a conda environment, and another user already reported that this library might not work well using conda.

**Comment by ryanpeach** [comment] 2017-09-27 03:20
I've confirmed this doesn't really work anyway, deap needs you give it a pool from within an "if __name__=="__main__"" structure for it to work (which means the user needs to do it themselves, but we can give them a param to do it).

**Comment by rsteca** [comment] 2017-10-21 22:35
This should be fixed in the 0.2.2 version

**Closed by rsteca** 2017-10-21 22:35 UTC
